components:
  parameters:
    offset:
      name: offset
      in: query
      required: false
      schema:
        type: integer
        format: int32
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        format: int32
