---
did:
  - changed-files:
      - any-glob-to-any-file:
          - modules/did/**/*
didcomm:
  - changed-files:
      - any-glob-to-any-file:
          - modules/didcomm/**/*
connections:
  - changed-files:
      - any-glob-to-any-file:
          - modules/connections/**/*
credentials:
  - changed-files:
      - any-glob-to-any-file:
          - modules/credentials/**/*
cloud-agent:
  - changed-files:
      - any-glob-to-any-file:
          - cloud-agent/**/*
api-server:
  - changed-files:
      - any-glob-to-any-file:
          - modules/api-server/**/*
wallet-management:
  - changed-files:
      - any-glob-to-any-file:
          - modules/wallet-management/**/*
notifications:
  - changed-files:
      - any-glob-to-any-file:
          - modules/notifications/**/*
vdr:
  - changed-files:
      - any-glob-to-any-file:
          - modules/vdr/**/*
shared:
  - changed-files:
      - any-glob-to-any-file:
          - modules/shared/**/*
prism-node:
  - changed-files:
      - any-glob-to-any-file:
          - prism-node/**/*
infra:
  - changed-files:
      - any-glob-to-any-file:
          - infrastructure/**/*
build:
  - changed-files:
      - any-glob-to-any-file:
          - project/**/*
          - build.sbt
          - version.sbt
          - package*.json
ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
docs:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**/*
          - README.md
