apiVersion: v1
kind: Service
metadata:
  name: agent-server-tapir-service
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: {{ include "cloud-agent.fullname" . }}-server
    app.kubernetes.io/service: {{ include "cloud-agent.fullname" . }}-server-main
    {{ template "labels.common" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "cloud-agent.fullname" . }}-server
  ports:
    - name: {{ include "cloud-agent.fullname" . }}-server-main
      protocol: "TCP"
      port: 8085
      targetPort: 8085
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: agent-server-didcomm-service
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: {{ include "cloud-agent.fullname" . }}-server
    app.kubernetes.io/service: {{ include "cloud-agent.fullname" . }}-server-didcomm
    {{ template "labels.common" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "cloud-agent.fullname" . }}-server
  ports:
    - name: {{ include "cloud-agent.fullname" . }}-server-didcomm
      protocol: "TCP"
      port: 8090
      targetPort: 8090
  type: ClusterIP

---

{{- if .Values.ingress.enabled }}
kind: Service
apiVersion: v1
metadata:
  name:  agent-domain-name-fake-service
  namespace: "{{ .Release.Namespace }}"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ join ", " .Values.ingress.applicationUrls }}"
  labels:
    app.kubernetes.io/name: {{ include "cloud-agent.fullname" . }}-server
    app.kubernetes.io/service: agent-server-domain-name-fake
    {{ template "labels.common" . }}
spec:
  type: ExternalName
  externalName: {{ .Values.ingress.platformIngressUrl }}
{{- end }}
