apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: StringSecret
metadata:
  name: "agent-keycloak-client-secret"
  namespace: {{ .Release.Namespace }}
spec:
  forceRegenerate: false
  fields:
    - fieldName: "secret"
      encoding: "base64"
      length: "16"
