apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: StringSecret
metadata:
  name: "keycloak-admin-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    {{ template "labels.common" . }}
spec:
  forceRegenerate: false
  fields:
    - fieldName: "password"
      encoding: "base64"
      length: "32"
    - fieldName: "postgres-password"
      encoding: "base64"
      length: "32"
