{{- if .Values.ingress.enabled }}
kind: Service
apiVersion: v1
metadata:
  name:  keycloak-domain-name-fake-service
  namespace: "{{ .Release.Namespace }}"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ join ", " .Values.ingress.applicationUrls }}"
  labels:
    app.kubernetes.io/name: keycloak-server
    app.kubernetes.io/service: keycloak-server-domain-name-fake-service
    {{ template "labels.common" . }}
spec:
  type: ExternalName
  externalName: {{ .Values.ingress.platformIngressUrl }}
{{- end }}
