version: '3.8'

services:

  ##########################
  # Databases
  ##########################
  db_castor:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: castor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data_castor_db:/var/lib/postgresql/data

  # delay to ensure DB is up before applying migrations
  db_castor_init_delay:
    image: alpine:3
    command: sleep 5
    depends_on:
      db_castor:
        condition: service_started

  db_castor_init:
    image: flyway/flyway:9.3.0-alpine
    volumes:
      - $PWD/castor/lib/sql-doobie/src/main/resources/sql:/flyway/sql
    command: -url=jdbc:postgresql://db_castor:5432/castor?user=postgres&password=postgres migrate
    depends_on:
      db_castor_init_delay:
        condition: service_completed_successfully

  ##########################
  # Services
  ##########################
  mercury:
    image: atala-prism.io/mercury-mediator:0.1.0-SNAPSHOT

  iris:
    image: atala-prism.io/iris-server:0.1.0-SNAPSHOT
    ports:
      - 8081:8081

  prism-agent:
    image: atala-prism.io/prism-agent-server:0.1.0-SNAPSHOT
    environment:
      IRIS_HOST: iris
      IRIS_PORT: 8081
      CASTOR_DB_HOST: db_castor
      CASTOR_DB_PORT: 5432
      CASTOR_DB_NAME: castor
      CASTOR_DB_USER: postgres
      CASTOR_DB_PASSWORD: postgres
    depends_on:
      db_castor_init:
        condition: service_completed_successfully

  swagger-ui:
    image: swaggerapi/swagger-ui:v4.14.0
    environment:
      - 'URLS=[
          { name: "PrismAgent", url: "/prism-agent/api/openapi-spec.yaml" },
          { name: "Mercury", url: "/mercury/api/openapi-spec.yaml" }
        ]'
      - BASE_URL=/apidocs

  haproxy:
    image: haproxy:2.6.5
    ports:
      - "80:80"   # Http
    depends_on:
      - mercury
      - prism-agent
      - swagger-ui
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro

volumes:
  pg_data_castor_db:
