version: '3.8'

services:

  mercury:
    image: atala-prism.io/mercury-mediator:0.1.0-SNAPSHOT

  prism-agent:
    image: atala-prism.io/prism-agent-server:0.1.0-SNAPSHOT

  swagger-ui:
    image: swaggerapi/swagger-ui:v4.14.0
    environment:
      - 'URLS=[
          { name: "PrismAgent", url: "/prism-agent/api/openapi-spec.yaml" },
          { name: "Mercury", url: "/mercury/api/openapi-spec.yaml" }
        ]'
      - BASE_URL=/apidocs

  haproxy:
    image: haproxy:2.6.5
    ports:
      - "80:80"   # Http
    depends_on:
      - mercury
      - prism-agent
      - swagger-ui
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro