version: '3.8'

services:

  ##########################
  # Castor Database
  ##########################
  db_castor:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: castor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data_castor_db:/var/lib/postgresql/data

  # delay to ensure DB is up before applying migrations
  db_castor_init_delay:
    image: alpine:3
    command: sleep 5
    depends_on:
      db_castor:
        condition: service_started

  ##########################
  # Pollux Database
  ##########################

  db_pollux:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: pollux
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - pg_data_pollux_db:/var/lib/postgresql/data

  # delay to ensure DB is up before applying migrations
  db_pollux_init_delay:
    image: alpine:3
    command: sleep 5
    depends_on:
      db_pollux:
        condition: service_started

  ##########################
  # Iris Database
  ##########################

  db_iris:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: iris
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
    volumes:
      - pg_data_iris_db:/var/lib/postgresql/data

  # delay to ensure DB is up before applying migrations
  db_iris_init_delay:
    image: alpine:3
    command: sleep 5
    depends_on:
      db_iris:
        condition: service_started


  ##########################
  # Services
  ##########################
  mediator:
    image: ghcr.io/input-output-hk/mercury-mediator:0.1.0-SNAPSHOT

  iris:
    image: ghcr.io/input-output-hk/iris-service:0.1.0-SNAPSHOT
    ports:
      - 8081:8081
    environment:
      IRIS_DB_HOST: db_iris
      IRIS_DB_PORT: 5432
      IRIS_DB_NAME: iris
      IRIS_DB_USER: postgres

  prism-agent:
    image: ghcr.io/input-output-hk/prism-agent:0.2.0-SNAPSHOT
    environment:
      IRIS_HOST: iris
      IRIS_PORT: 8081
      CASTOR_DB_HOST: db_castor
      CASTOR_DB_PORT: 5432
      CASTOR_DB_NAME: castor
      CASTOR_DB_USER: postgres
      CASTOR_DB_PASSWORD: postgres
      POLLUX_DB_HOST: db_pollux
      POLLUX_DB_PORT: 5432
      POLLUX_DB_NAME: pollux
      POLLUX_DB_USER: postgres
      POLLUX_DB_PASSWORD: postgres
      
  swagger-ui:
    image: swaggerapi/swagger-ui:v4.14.0
    environment:
      - 'URLS=[
          { name: "PrismAgent", url: "/prism-agent/api/openapi-spec.yaml" },
          { name: "Mediator", url: "/mediator/api/openapi-spec.yaml" }
        ]'
      - BASE_URL=/apidocs

  haproxy:
    image: haproxy:2.6.5
    ports:
      - "80:80"   # Http
    depends_on:
      - mediator
      - prism-agent
      - swagger-ui
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro

volumes:
  pg_data_castor_db:
  pg_data_pollux_db:
  pg_data_iris_db:
