components:
  parameters:
    didRefInPath:
      in: path
      name: didRef
      required: true
      description: DID reference.
      schema:
        type: string
      example: did:prism:4a5b5cf0a513e83b598bbea25cd6196746747f361a73ef77068268bc9bd732ff
    didOperationRefInPath:
      in: path
      name: didOperationRef
      required: true
      description: DID Operation Reference.
      schema:
        type: string
    didRefInQuery:
      in: query
      name: didRef
      required: true
      description: DID reference
      schema:
        type: string
