apiVersion: v1
entries:
  prism-agent:
    - apiVersion: v2
      appVersion: 1.19.0
      created: "2023-11-21T13:45:58.275344618Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: faa036cfc70e35ca0ada898e4c0281f70a06d8855f55e37f24f9b529895b4a64
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.19.0.tgz
      version: 1.19.0
    - apiVersion: v2
      appVersion: 1.18.0
      created: "2023-11-21T13:45:58.265256577Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: 5a803d916bc19c824aec9d39efb0206ff9a2a3b1932b276acaaf97c580f62387
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.18.0.tgz
      version: 1.18.0
    - apiVersion: v2
      appVersion: 1.17.0
      created: "2023-11-21T13:45:58.261459189Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: a53050003aedfd0a7d78014dfe9e819c6e2a1db442eeaac6971cff354cf0d3d4
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.17.0.tgz
      version: 1.17.0
    - apiVersion: v2
      appVersion: 1.16.4
      created: "2023-11-21T13:45:58.258626383Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: 05c9159bea902724bb8c8c395bb00d5a3305602e8ace94fe0dd94c1064384fc5
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.16.4.tgz
      version: 1.16.4
    - apiVersion: v2
      appVersion: 1.16.3
      created: "2023-11-21T13:45:58.255623789Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: 309200472891b513a19fad3c3a84745ee95afad6b4680924e81b497f4d8736d3
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.16.3.tgz
      version: 1.16.3
    - apiVersion: v2
      appVersion: 1.16.2
      created: "2023-11-21T13:45:58.252198434Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: 0ffa1f3b0748da032ff40900bc4bb55e4a64c400b31cc8796880da4aa7557529
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.16.2.tgz
      version: 1.16.2
generated: "2023-11-21T13:45:58.248988181Z"
