apiVersion: v1
entries:
  prism-agent:
    - apiVersion: v2
      appVersion: 1.26.0
      created: "2024-02-06T17:37:42.463709972Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: f3405b5bd8c3522a62a5130b5e6733c519a7c88f1ad37c85ee608a4115e087f9
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.26.0.tgz
      version: 1.26.0
    - apiVersion: v2
      appVersion: 1.25.0
      created: "2024-02-06T17:37:42.453435405Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 4bfbd942f4d6371157f9762fa52a3ec62e1d064c200fe770f287b0f34f36e676
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.25.0.tgz
      version: 1.25.0
    - apiVersion: v2
      appVersion: 1.24.0
      created: "2024-02-06T17:37:42.444200011Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 368e8b81d34e54e244779ed218b6a6885b56f1616f761b2b217a13e21fb5078a
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.24.0.tgz
      version: 1.24.0
    - apiVersion: v2
      appVersion: 1.23.0
      created: "2024-02-06T17:37:42.43342009Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: cd1a3beba47786eb5ee388a6761484b628a797802d504e815c119526afaa91f7
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.23.0.tgz
      version: 1.23.0
    - apiVersion: v2
      appVersion: 1.22.0
      created: "2024-02-06T17:37:42.422649911Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: be3d146eba5e099d7f2e7cf9338a4a6cb238f19cb3f458864fe88778505bd403
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.22.0.tgz
      version: 1.22.0
    - apiVersion: v2
      appVersion: 1.21.1
      created: "2024-02-06T17:37:42.413039604Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: d97c1d2dc3f9dadb8642271b89ff2c2fb52f01e00c8aa5ca712ee1ccb77622d0
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.21.1.tgz
      version: 1.21.1
    - apiVersion: v2
      appVersion: 1.21.0
      created: "2024-02-06T17:37:42.402602736Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 12de363c93d6155ae492710ca6a365b5a4b429d40b0691f289528b7ac08119b2
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.21.0.tgz
      version: 1.21.0
    - apiVersion: v2
      appVersion: 1.20.1
      created: "2024-02-06T17:37:42.392079833Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 7890f9939ae1a0a143915d36ec3c401384195ccbeabee03fb921837b75aefb76
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.20.1.tgz
      version: 1.20.1
    - apiVersion: v2
      appVersion: 1.20.0
      created: "2024-02-06T17:37:42.382459361Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 004a72bf116850fa79017d94880684a9aac798a11825ce5b88ac4b34ed0dc862
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.20.0.tgz
      version: 1.20.0
    - apiVersion: v2
      appVersion: 1.19.1
      created: "2024-02-06T17:37:42.372169391Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 077292fe1e1388a9d5db10b0e28869c2754928defa25f5a59dd12431bd058ba7
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.19.1.tgz
      version: 1.19.1
    - apiVersion: v2
      appVersion: 1.19.0
      created: "2024-02-06T17:37:42.362827256Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: faa036cfc70e35ca0ada898e4c0281f70a06d8855f55e37f24f9b529895b4a64
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.19.0.tgz
      version: 1.19.0
    - apiVersion: v2
      appVersion: 1.18.0
      created: "2024-02-06T17:37:42.351899496Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: 5a803d916bc19c824aec9d39efb0206ff9a2a3b1932b276acaaf97c580f62387
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.18.0.tgz
      version: 1.18.0
    - apiVersion: v2
      appVersion: 1.17.0
      created: "2024-02-06T17:37:42.349077633Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: a53050003aedfd0a7d78014dfe9e819c6e2a1db442eeaac6971cff354cf0d3d4
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.17.0.tgz
      version: 1.17.0
    - apiVersion: v2
      appVersion: 1.16.4
      created: "2024-02-06T17:37:42.346249568Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: 05c9159bea902724bb8c8c395bb00d5a3305602e8ace94fe0dd94c1064384fc5
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.16.4.tgz
      version: 1.16.4
    - apiVersion: v2
      appVersion: 1.16.3
      created: "2024-02-06T17:37:42.342752475Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: 309200472891b513a19fad3c3a84745ee95afad6b4680924e81b497f4d8736d3
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.16.3.tgz
      version: 1.16.3
    - apiVersion: v2
      appVersion: 1.16.2
      created: "2024-02-06T17:37:42.339903771Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: 0ffa1f3b0748da032ff40900bc4bb55e4a64c400b31cc8796880da4aa7557529
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.16.2.tgz
      version: 1.16.2
generated: "2024-02-06T17:37:42.336724016Z"
