name: Connect testing workflow

# Cancel previously running workflows if new commit pushed to the branch
# this will help to push fixes earlier and stop previous workflows
concurrency:
  group: ${{ github.head_ref }}${{ github.ref }}-connect
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/connect.yml"
      - ".github/workflows/scala-unit-tests.yml"
      - "connect/lib/**"
  pull_request:
    paths:
      - ".github/workflows/connect.yml"
      - ".github/workflows/scala-unit-tests.yml"
      - "connect/lib/**"

jobs:
  build-and-test-mercury:
    uses: ./.github/workflows/scala-unit-tests.yml
    with:
      component-name: "Connect Lib"
      component-dir: "connect/lib"
    secrets: inherit
