name: Deployment

on:
  push:
    tags:
      - "cloud-agent-v*"

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Parse input parameters
        id: parse-params
        run: |
          tag_name=${{ github.ref_name }}
          if [[ $tag_name =~ cloud-agent-(.*) ]]; then
            version=${BASH_REMATCH[1]}
            echo "Version: $version"
            echo "::set-output name=version::$version"
          fi

      - name: Trigger deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ATALA_GITHUB_TOKEN }}
          repository: input-output-hk/atala-prism-non-prod-argocd-state
          event-type: trigger-cloud-agent
          client-payload: '{"version": "${{ steps.parse-params.outputs.version }}"}'
