name: File Hygiene

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    uses: hyperledger-identus/.github/.github/workflows/lint-files.yml@5bdb1e5a46ae66e6bcaa550de3e1e6cc26c0b47d # main
