name: Integration tests

concurrency:
  group: ${{ github.head_ref }}${{ github.ref }}-integration-tests
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - "main"

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  run-integration-tests-neoprism:
    name: "Run integration tests (neoprism)"
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '[skip ci]') }}
    env:
      LOGS_DIR: "tests/integration-tests/target/logs"
      REPORTS_DIR: "tests/integration-tests/target/site/serenity"
      DOCKER_API_VERSION: "1.44"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK 21 (Temurin) with sbt cache
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0 pinned
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - name: Set up sbt
        uses: sbt/setup-sbt@dd1ef7d7798fab5ce802a6adab3b782817b8c2d0 # v1.1.18 pinned

      - name: Setup Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: hyperledger-bot
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Compose
        uses: ndeloof/install-compose-action@4a33bc31f327b8231c4f343f6fba704fedc0fa23 # v0.0.1
        with:
          version: v2.29.2 # align with Docker 27.x
          legacy: true # will also install in PATH as `docker-compose`

      - name: Build local version of Cloud Agent
        id: build_local_cloud_agent
        env:
          ENV_FILE: "infrastructure/local/.env"
          GITHUB_ACTOR: hyperledger-bot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt docker:publishLocal
          echo "agent_version=$(cut -d'=' -f2 version.sbt | tr -d '" ')" >> "${GITHUB_OUTPUT}"
          echo "prism_node_version=$(grep PRISM_NODE_VERSION infrastructure/local/.env | cut -d'=' -f2 | tr -d ' ')" >> "${GITHUB_OUTPUT}"
          echo "neoprism_version=$(grep NEOPRISM_VERSION infrastructure/local/.env | cut -d'=' -f2 | tr -d ' ')" >> "${GITHUB_OUTPUT}"

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0 pinned
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "sbt"

      - name: Set up sbt
        uses: sbt/setup-sbt@dd1ef7d7798fab5ce802a6adab3b782817b8c2d0 # v1.1.18 pinned

      - name: Run integration tests (neoprism)
        working-directory: "tests/integration-tests"
        env:
          PRISM_NODE_VERSION: ${{ steps.build_local_cloud_agent.outputs.prism_node_version }}
          AGENT_VERSION: ${{ steps.build_local_cloud_agent.outputs.agent_version }}
          GITHUB_ACTOR: hyperledger-bot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEOPRISM_VERSION: ${{ steps.build_local_cloud_agent.outputs.neoprism_version }}
          TESTS_CONFIG: /configs/basic_neoprism.conf
          VDR_MEMORY_DRIVER_ENABLED: "true"
          VDR_DATABASE_DRIVER_ENABLED: "true"
        #        continue-on-error: true
        run: |
          export DOCKER_API_VERSION=1.44
          export DOCKER_HOST=unix:///var/run/docker.sock
          ./gradlew test --tests "IntegrationTestsRunner" -Dcucumber.filter.tags="not @vdr_memory_and_db and not @vdr_ledger"

      - name: Make report of integration tests (neoprism)
        working-directory: "tests/integration-tests"
        if: always()
        env:
          PRISM_NODE_VERSION: ${{ steps.build_local_cloud_agent.outputs.prism_node_version }}
          AGENT_VERSION: ${{ steps.build_local_cloud_agent.outputs.agent_version }}
          GITHUB_ACTOR: hyperledger-bot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEOPRISM_VERSION: ${{ steps.build_local_cloud_agent.outputs.neoprism_version }}
          TESTS_CONFIG: /configs/basic_neoprism.conf
          VDR_MEMORY_DRIVER_ENABLED: "true"
          VDR_DATABASE_DRIVER_ENABLED: "true"
        run: |
          export DOCKER_API_VERSION=1.44
          export DOCKER_HOST=unix:///var/run/docker.sock
          ./gradlew reports -Dcucumber.filter.tags="not @vdr_memory_and_db and not @vdr_ledger and not @deactivate"

      - name: Extract test results
        working-directory: "tests/integration-tests"
        id: analyze_test_results
        if: github.ref_name == 'main' && always()
        run: |
          JSON_RESULTS="target/site/serenity/serenity-summary.json"
          CONCLUSION=failure
          TOTAL_TESTS=0
          FAILED_TESTS=0
          SKIPPED_TESTS=0
          TESTS_WITH_ERRORS=0
          if [ -f "${JSON_RESULTS}" ]; then
            TOTAL_TESTS="$(cat ${JSON_RESULTS} | jq '.results.counts.total')"
            PENDING_TESTS="$(cat ${JSON_RESULTS} | jq '.results.counts.pending')"
            SKIPPED_TESTS="$(cat ${JSON_RESULTS} | jq '.results.counts.skipped')"
            IGNORED_TESTS="$(cat ${JSON_RESULTS} | jq '.results.counts.ignored')"
            FAILED_TESTS="$(cat ${JSON_RESULTS} | jq '.results.counts.failure')"
            TESTS_WITH_ERRORS="$(cat ${JSON_RESULTS} | jq '.results.counts.error')"
            if [[ ${FAILED_TESTS} == 0 && ${TESTS_WITH_ERRORS} == 0 ]] ; then
              CONCLUSION=success
            fi
          fi
          {
            echo "conclusion=${CONCLUSION}";
            echo "tests=${TOTAL_TESTS}";
            echo "failures=${FAILED_TESTS}";
            echo "errors=${TESTS_WITH_ERRORS}";
            echo "pending=${PENDING_TESTS}";
            echo "skipped=${SKIPPED_TESTS}";
            echo "ignored=${IGNORED_TESTS}";
          } >> "$GITHUB_OUTPUT"

      - name: Publish e2e test Results (neoprism)
        id: publish-unit-tests
        uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
        with:
          junit_files: "${{ env.REPORTS_DIR }}/SERENITY-JUNIT-*.xml"
          comment_title: "Integration Test Results"
          check_name: "Integration Test Results"

      - name: Upload serenity report (neoprism)
        if: github.ref_name == 'main' || failure()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: integration-tests-result
          path: ${{ env.REPORTS_DIR }}
          compression-level: 9

      - name: Upload logs (neoprism)
        if: github.ref_name == 'main' || failure()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: docker-logs
          path: ${{ env.LOGS_DIR }}
          compression-level: 9

      - name: Slack Notification (neoprism)
        if: github.ref_name == 'main' && failure()
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_COLOR: ${{ steps.analyze_test_results.outputs.conclusion }}
          SLACK_MESSAGE: |
            Total: ${{ steps.analyze_test_results.outputs.tests }}
            Failed: ${{ steps.analyze_test_results.outputs.failures }}
            Errors in tests: ${{ steps.analyze_test_results.outputs.errors }}
            Skipped (known bugs): ${{ steps.analyze_test_results.outputs.skipped }}
          SLACK_TITLE: "Identus Cloud Agent Integration Tests: ${{ steps.analyze_test_results.outputs.conclusion }}"
          SLACK_USERNAME: circleci
          SLACK_WEBHOOK: ${{ secrets.E2E_TESTS_SLACK_WEBHOOK }}

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v4.4.0
        with:
          node-version: 20

      - name: Run didcomm tests
        working-directory: "tests/didcomm-tests"
        env:
          AGENT_VERSION: ${{ steps.build_local_cloud_agent.outputs.agent_version }}
        run: |
          ./docker/run.sh "$AGENT_VERSION"
          npm i
          npm test
          ./docker/stop.sh

  run-integration-tests-prism-node:
    name: "Run integration tests (prism-node)"
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '[skip ci]') }}
    env:
      LOGS_DIR: "tests/integration-tests/target/logs"
      REPORTS_DIR: "tests/integration-tests/target/site/serenity"
      DOCKER_API_VERSION: "1.44"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK 21 (Temurin) with sbt cache
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0 pinned
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - name: Set up sbt
        uses: sbt/setup-sbt@dd1ef7d7798fab5ce802a6adab3b782817b8c2d0 # v1.1.18 pinned

      - name: Setup Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: hyperledger-bot
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Compose
        uses: ndeloof/install-compose-action@4a33bc31f327b8231c4f343f6fba704fedc0fa23 # v0.0.1
        with:
          version: v2.29.2
          legacy: true

      - name: Build local version of Cloud Agent
        id: build_local_cloud_agent_prism
        env:
          ENV_FILE: "infrastructure/local/.env"
          GITHUB_ACTOR: hyperledger-bot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt docker:publishLocal
          echo "agent_version=$(cut -d'=' -f2 version.sbt | tr -d '\" ')" >> "${GITHUB_OUTPUT}"
          echo "prism_node_version=$(grep PRISM_NODE_VERSION infrastructure/local/.env | cut -d'=' -f2 | tr -d ' ')" >> "${GITHUB_OUTPUT}"

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0 pinned
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "sbt"

      - name: Set up sbt
        uses: sbt/setup-sbt@dd1ef7d7798fab5ce802a6adab3b782817b8c2d0 # v1.1.18 pinned

      - name: Run integration tests (prism-node)
        working-directory: "tests/integration-tests"
        env:
          PRISM_NODE_VERSION: ${{ steps.build_local_cloud_agent_prism.outputs.prism_node_version }}
          AGENT_VERSION: ${{ steps.build_local_cloud_agent_prism.outputs.agent_version }}
          GITHUB_ACTOR: hyperledger-bot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TESTS_CONFIG: /configs/basic.conf
          VDR_LEDGER_DRIVER: prism-node
          VDR_PRISM_NODE_DRIVER_ENABLED: "true"
          VDR_MEMORY_DRIVER_ENABLED: "true"
          VDR_DATABASE_DRIVER_ENABLED: "true"
        run: |
          export DOCKER_API_VERSION=1.44
          export DOCKER_HOST=unix:///var/run/docker.sock
          ./gradlew test --tests "IntegrationTestsRunner" -Dcucumber.filter.tags="@vdr_ledger"

      - name: Make report of integration tests (prism-node)
        working-directory: "tests/integration-tests"
        if: always()
        env:
          PRISM_NODE_VERSION: ${{ steps.build_local_cloud_agent_prism.outputs.prism_node_version }}
          AGENT_VERSION: ${{ steps.build_local_cloud_agent_prism.outputs.agent_version }}
          GITHUB_ACTOR: hyperledger-bot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TESTS_CONFIG: /configs/basic.conf
          VDR_LEDGER_DRIVER: prism-node
          VDR_PRISM_NODE_DRIVER_ENABLED: "true"
          VDR_MEMORY_DRIVER_ENABLED: "true"
          VDR_DATABASE_DRIVER_ENABLED: "true"
        run: |
          export DOCKER_API_VERSION=1.44
          export DOCKER_HOST=unix:///var/run/docker.sock
          ./gradlew reports -Dcucumber.filter.tags="@vdr_ledger"

      - name: Publish e2e test Results (prism-node)
        id: publish-unit-tests-prism
        uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
        with:
          junit_files: "${{ env.REPORTS_DIR }}/SERENITY-JUNIT-*.xml"
          comment_title: "Integration Test Results (prism-node)"
          check_name: "Integration Test Results (prism-node)"

      - name: Upload serenity report (prism-node)
        if: github.ref_name == 'main' || failure()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: integration-tests-result-prism-node
          path: ${{ env.REPORTS_DIR }}
          compression-level: 9

      - name: Upload logs (prism-node)
        if: github.ref_name == 'main' || failure()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: docker-logs-prism-node
          path: ${{ env.LOGS_DIR }}
          compression-level: 9
