name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v5
