name: Prism node client testing workflow

# Cancel previously running workflows if new commit pushed to the branch
# this will help to push fixes earlier and stop previous workflows
concurrency:
  group: ${{ github.head_ref }}${{ github.ref }}-prism-node-client
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/prism-node-client.yml"
      - ".github/workflows/scala-unit-tests.yml"
      - "prism-node/client/**"
  pull_request:
    paths:
      - ".github/workflows/prism-node-client.yml"
      - ".github/workflows/scala-unit-tests.yml"
      - "prism-node/client/**"

jobs:
  build-and-test-prism-node-client:
    uses: ./.github/workflows/scala-unit-tests.yml
    with:
      component-name: "PRISM Node Client"
      component-dir: "prism-node/client/scala-client"
    secrets: inherit
