name: Testing workflow

# Cancel previously running workflows if new commit pushed to the branch
# this will help to push fixes earlier and stop previous workflows
concurrency:
  group: ${{ github.head_ref }}${{ github.ref }}-all
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build-and-test-castor:
    uses: ./.github/workflows/scala-unit-tests.yml
    with:
      component-name: "Atala PRISM"
      component-dir: "."
    secrets: inherit
